### ISSUE TITLE
apigee-r-instance-template.jinja missing

### ISSUE THREAD

**Issue by mukundha** [apigee/edge-gcp#3]
After i get rid of error issue #2 by commenting it out - this is the next error 

ERROR: (gcloud.deployment-manager.deployments.create) Error in Operation [operation-1495600909495-5503db8efaad8-430c10a5-120a756a]: errors:
- code: INVALID_CONFIG
  message: 'Invalid config files: Template fetching failed: Failed to find imported
    template ''apigee-r-instance-template.jinja'' for resource {name=devjam-apigee-rmp-as-it,
    properties={APIGEE_ADMIN_EMAIL=opdk@apigee.com, APIGEE_ADMINPW=Secret123, HOST_NAMES=$(ref.devjam-apigee-ds1.networkInterfaces[0].networkIP):$(ref.devjam-apigee-ds2.networkInterfaces[0].networkIP):$(ref.devjam-apigee-ax0.networkInterfaces[0].networkIP):$(ref.devjam-apigee-ax1.networkInterfaces[0].networkIP):$(ref.devjam-apigee-dp.networkInterfaces[0].networkIP),

**Comment by rajeshm7910** [comment]
This is added
